name: Crown
version: '1.0'
main: cp.corona.crown.Crown
api-version: '1.18'
depend: [PlaceholderAPI]

commands:
  crown:
    description: Main command for Crown.
    usage: /<command> [punish|reload|help|unpunish|history|profile|locker]

  punish:
    description: Alias for /crown punish command.
    usage: /<command> <player> [type] [time] [reason]

  unpunish:
    description: Command to directly unpunish players.
    usage: /<command> <player> <type> [reason]

  check:
    description: Command to check a punishment by ID.
    usage: /<command> <id> [info|repunish|unpunish]
    aliases: [c]

  history:
    description: Command to view a player's punishment history.
    usage: /<command> <player>

  profile:
    description: Command to view a player's profile.
    usage: /<command> <player>

  locker:
    description: Command to open lockers.
    usage: /<command> [player|all]

  report: # ADDED
    description: Command to report a player or a server issue.
    usage: /<command> [player]

  reports: # ADDED
    description: Command for moderators to view and manage reports.
    usage: /<command>

  softban:
    description: Command to directly softban players.
    usage: /<command> <player> [time] [reason]

  freeze:
    description: Command to directly freeze players for manual review.
    usage: /<command> <player> [reason]
  ban:
    description: Command to directly ban players.
    usage: /<command> <player> [time] [reason]
  kick:
    description: Command to directly kick players.
    usage: /<command> <player> [reason]
  mute:
    description: Command to directly mute players.
    usage: /<command> <player> [time] [reason]
  warn:
    description: Command to directly warn players.
    usage: /<command> <player> [reason]
  unban:
    description: Command to directly unban players.
    usage: /<command> <player> [reason]
  unwarn:
    description: Command to directly unwarn players.
    usage: /<command> <player> [reason]
  unmute:
    description: Command to directly unmute players.
    usage: /<command> <player> [reason]
  unfreeze:
    description: Command to directly unfreeze players.
    usage: /<command> <player> [reason]
  unsoftban:
    description: Command to directly unsoftban players.
    usage: /<command> <player> [reason]
  fchat:
    description: Toggle participation in freeze chat.
    usage: /<command> <player|#ID>
  mod:
    description: Toggles moderator mode.
    usage: /<command>


permissions:
  crown.use:
    description: Allows player to use basic crown commands and punish menu
    default: op
  crown.report.create: # MODIFIED
    description: Allows player to use the /report command (if require-permission is true in config).
    default: op
  crown.report.view:
    description: Allows player to use the /reports command to manage reports.
    default: op
  crown.report.assign: # ADDED
    description: Allows a moderator to assign a report to another moderator.
    default: op
  crown.report.bypasscooldown:
    description: Allows player to bypass report cooldowns and rate limits.
    default: op
  crown.profile:
    description: Allows player to use the profile command
    default: op
  crown.profile.editinventory:
    description: Allows player to edit inventories through the profile menu
    default: op
  crown.check:
    description: Allows player to check punishments by ID
    default: op
  crown.history:
    description: Allows player to view punishment history
    default: op
  crown.fchat:
    description: Allows player to receive frozen player messages
    default: op
  crown.admin:
    description: Allows player to use reload command
    default: op
  crown.punish.ban:
    description: Allows player to use ban related features
    default: op
  crown.unpunish.ban:
    description: Allows player to use unban related features
    default: op
  crown.punish.mute:
    description: Allows player to use mute related features
    default: op
  crown.unpunish.mute:
    description: Allows player to use unmute related features
    default: op
  crown.punish.softban:
    description: Allows player to use softban related features
    default: op
  crown.unpunish.softban:
    description: Allows player to use unsoftban related features
    default: op
  crown.punish.kick:
    description: Allows player to use kick related features
    default: op
  crown.punish.warn:
    description: Allows player to use warn related features
    default: op
  crown.punish.freeze:
    description: Allows player to use freeze related features
    default: op
  crown.unpunish.freeze:
    description: Allows player to use unfreeze related features
    default: op
  crown.bypass.softban:
    description: Allows player to bypass softbans
    default: op
  crown.bypass.freeze:
    description: Allows player to bypass freeze punishment
    default: op
  crown.bypass.ban:
    description: Allows player to bypass ban punishment
    default: op
  crown.bypass.mute:
    description: Allows player to bypass mute punishment
    default: op
  crown.bypass.warn:
    description: Allows player to bypass warn punishment
    default: op
  crown.bypass.kick:
    description: Allows player to bypass kick punishment
    default: op
  crown.mod.use:
    description: Allows player to use the /mod command and enter moderator mode.
    default: op
  crown.mod.seevanish:
    description: Allows player to see other moderators who are in vanish mode.
    default: op
  crown.locker.admin:
    description: Allows modifying other moderators' lockers.
    default: op
