name: CrownPunishments
version: '1.0.1'
main: cp.corona.crownpunishments.CrownPunishments
api-version: '1.18'
softdepend: [PlaceholderAPI]

commands:
  crown:
    description: Main command for CrownPunishments.
    usage: /<command> [punish|reload|help|unpunish]
    aliases: [cp, crownpunish]
    permission: crown.use
    permission-message: You do not have permission to use this command.
  punish: # Alias command for direct /punish usage - ALIAS OF /CROWN PUNISH
    description: Alias for /crown punish command.
    usage: /<command> <player> [type] [time] [reason]
    permission: crown.use
    permission-message: You do not have permission to use this command.
  crownpunishments: # Added another alias example, for consistency and discoverability - ALIAS OF /CROWN
    description: Alias for /crown command - full name alias
    usage: /<command> [punish|reload|help|unpunish]
    aliases: [crown]
    permission: crown.use
    permission-message: You do not have permission to use this command.
  unpunish: # Top level command for unpunishing players directly - SEPARATE TOP LEVEL COMMAND
    description: Command to directly unpunish players.
    usage: /<command> <player> <type>
    permission: crown.admin
    permission-message: You do not have permission to use this command.
  softban: # Top level command for softbanning players directly - SEPARATE TOP LEVEL COMMAND, MIRRORS /CROWN PUNISH SOFTBAN
    description: Command to directly softban players.
    usage: /<command> <player> [time] [reason]
    permission: crown.use # or crown.admin if you want to restrict it to admins only
    permission-message: You do not have permission to use this command.
  freeze: # Top level command for freezing players directly - SEPARATE TOP LEVEL COMMAND, MIRRORS /crown punish freeze - NEW
    description: Command to directly freeze players for manual review. # Description for /freeze command - NEW
    usage: /<command> <player> [reason] # Usage for /freeze command - NEW - Reason is now optional
    permission: crown.use # or crown.admin if you want to restrict it to admins only - NEW
    permission-message: You do not have permission to use this command. # Permission message for /freeze - NEW


permissions:
  crown.use:
    description: Allows players to use the /crown and /punish commands to access punishment menus.
    default: op # or true if you want everyone to use it by default, consider 'op' for moderation tools
  crown.admin:
    description: Allows access to administrative commands like /crown reload and /crown unpunish.
    default: op
  crown.softban.bypass:
    description: Allows players to bypass softban command blocking.
    default: op
  crown.freeze.bypass: # Permission to bypass freeze restrictions - NEW
    description: Allows players to bypass freeze restrictions (movement, commands). # Description for freeze bypass permission - NEW
    default: op # Default to OP, adjust as needed - NEW